<div class = "social-links">
    <div>
        <div class="">
            Magento.loc sosial
        </div>
        <ul>
            <li>
                <a href="#">
                    <img src="http://www.magento.loc/skin/frontend/rwd/ProductTheme/images/social/facebook.png" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="http://www.magento.loc/skin/frontend/rwd/ProductTheme/images/social/instagram.png" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="http://www.magento.loc/skin/frontend/rwd/ProductTheme/images/social/pinterest.png" />
                </a>
            </li>
            <li>
                <a href="#">
                    <img src="http://www.magento.loc/skin/frontend/rwd/ProductTheme/images/social/twitter.png" />
                </a>
            </li>
        </ul>
    </div>
</div>